from pathlib import Path
from typing import Protocol

from pmagent.domain.models import Project, Task


class ClickUpPort(Protocol):
    def get_tasks(self, list_id: str) -> list[Task]: ...
    def get_task(self, task_id: str) -> Task: ...
    def create_task(
        self, list_id: str, title: str, description: str, priority: str | None = None
    ) -> Task: ...
    def update_task_status(self, task_id: str, status: str) -> None: ...
    def add_comment(self, task_id: str, comment: str) -> None: ...
    def search_tasks(self, workspace_id: str, query: str) -> list[Task]: ...
    def get_spaces(self, team_id: str) -> list[dict]: ...
    def get_lists(self, space_id: str) -> list[dict]: ...


class GitPort(Protocol):
    def current_branch(self) -> str: ...
    def list_branches(self) -> list[str]: ...
    def create_branch(self, name: str) -> None: ...
    def recent_commits(self, branch: str, count: int) -> list[dict]: ...
    def get_commit(self, sha: str) -> dict: ...


class ConfigPort(Protocol):
    def load(self, path: Path | None) -> Project: ...
    def find_config(self, start_dir: Path | None) -> Path: ...
